# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-lab
  labels:
    app: todo-backend
    env: dev
data:
  MONGO_HOST: "mongodb-svc" 
  USE_DB_AUTH: "true"
  PORT: "8080"  
